import type { CatalogueEntry } from '../api/contract.js';

/** The project's reviewed plugins. Reference plugins ship in the image. */
export const CATALOGUE: readonly Omit<CatalogueEntry, 'installed'>[] = [
  {
    package: '@ai-switchboard/source-webhook',
    displayName: 'Webhook',
    description: 'Any system that can POST JSON; map it with JSONata.',
    kinds: ['source'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/source-poll-http',
    displayName: 'Poll HTTP',
    description: 'Poll a JSON endpoint with a cursor.',
    kinds: ['source'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/source-github',
    displayName: 'GitHub',
    description: 'Pull requests, issues, check suites, releases, pushes.',
    kinds: ['source'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/source-linear',
    displayName: 'Linear',
    description: 'Issue label and state changes.',
    kinds: ['source'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/source-datadog',
    displayName: 'Datadog',
    description: 'Monitor alerts through a webhook integration.',
    kinds: ['source'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/destination-http',
    displayName: 'HTTP',
    description: 'Call any endpoint: sync, callback or fire-and-forget.',
    kinds: ['destination'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/destination-claude-routines',
    displayName: 'Claude Routines',
    description: 'Fire a routine; windows and daily allowance as meters.',
    kinds: ['destination'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/destination-github-actions',
    displayName: 'GitHub Actions',
    description: 'workflow_dispatch with billable-minute usage.',
    kinds: ['destination'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/destination-log',
    displayName: 'Log (testing)',
    description:
      'Logs every invocation and simulates outcomes, delays and a meter — for trying processes out.',
    kinds: ['destination'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/notifier-slack',
    displayName: 'Slack',
    description: 'Run outcomes and system alerts to a channel.',
    kinds: ['notifier'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/notifier-webhook',
    displayName: 'Webhook notifier',
    description: 'POST notifications as signed JSON.',
    kinds: ['notifier'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/secrets-env',
    displayName: 'Environment secrets',
    description: 'Resolve secret:// references from environment variables.',
    kinds: ['secret_provider'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
  {
    package: '@ai-switchboard/secrets-file',
    displayName: 'File secrets',
    description: 'Resolve references from mounted files (Kubernetes secrets).',
    kinds: ['secret_provider'],
    reviewed: true,
    latestVersion: '1.0.0',
  },
];
